**Problem - 1: Array Creation:**

1. Initialize an empty array with size 2X2.


In [ ]:
import numpy as np

empty_array = np.empty((2, 2))
print(empty_array)

[[4.72756005e-310 0.00000000e+000]
 [1.57068496e+246 6.75925326e-310]]


2. Initialize an all one array with size 4X2.

In [ ]:
one_array = np.ones((4, 2))
print(one_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.


In [ ]:
filled_array = np.full((3, 3),4)
filled_array

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

4. Return a new array of zeros with same shape and type as a given array.

In [ ]:
given_array = np.array([[1, 2], [3, 4]])
zeros_array = np.zeros_like(given_array)
print(zeros_array)

[[0 0]
 [0 0]]


 5. Return a new array of ones with same shape and type as a given array.

In [ ]:
ones_array = np.ones_like(given_array)
print(ones_array)

[[1 1]
 [1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.

In [ ]:
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print(numpy_array)

[1 2 3 4]


**Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**

1. Create an array with values ranging from 10 to 49.

In [ ]:
range_array = np.arange(10,49)
print(range_array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


2. Create a 3X3 matrix with values ranging from 0 to 8.

In [ ]:
matrix = np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.

In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.

In [ ]:
random_array = np.random.random(30)
mean_value = random_array.mean()
print(mean_value)

0.44817381378327353


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
random_array = np.random.randint(0,100,(10, 10))

# Find the minimum and maximum values in the array
min_value = random_array.min()
max_value = random_array.max()

print("Random Array:")
print(random_array)
print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)

Random Array:
[[18 93 71 58  8 70 81 54 56 22]
 [67 28 16 50  5 40 52 89 37 58]
 [26 38 15 53 61 17 96 45 43 67]
 [88 88 84 19 37 23 43 53 87 75]
 [27 34 10 82 35 45 62 81 78  8]
 [16 42 26 84 68 48  3 50 53 16]
 [90  0 62 62 60 83 41 96 98 46]
 [20 40  3 80 37 91 42 39 87 87]
 [46 55 64  0  4 45 40 39 52 29]
 [68 16 73 50 62 88 78 78 47 30]]

Minimum Value: 0
Maximum Value: 98


6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
zero_array = np.zeros(10)

# Replace the 5th element (index 4) with 1
zero_array[4] = 1

print(zero_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
arr = [1,2,0,0,4,0]
reverse_array = arr[::-1]
print(reverse_array)

[0, 4, 0, 0, 2, 1]


8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
array_2d = np.zeros((5, 5))

# Set the border elements to 1
array_2d[0, :] = 1  # Top row
array_2d[-1, :] = 1  # Bottom row
array_2d[:, 0] = 1  # Left column
array_2d[:, -1] = 1  # Right column

print(array_2d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**Problem - 3: Array Operations:**

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:

1. Add the two array.

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
print(np.add(x,y))

[[ 6  8]
 [10 13]]


2. Subtract the two array.

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
print(np.subtract(x,y))

[[-4 -4]
 [-4 -3]]


3. Multiply the array with any integers of your choice.

In [ ]:
x = np.array([[1,2],[3,5]])
print(np.multiply(x,10))

[[10 20]
 [30 50]]


4. Find the square of each element of the array.

In [ ]:
x = np.array([[1,2],[3,5]])
print(np.square(x))

[[ 1  4]
 [ 9 25]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

dot_vw = np.dot(v,w)
print("The dot product of v and w: ",dot_vw)

dot_xv = np.dot(x,v)
print("The dot product of x and v: ", dot_xv)

dot_xy = np.dot(x,y)
print("The dot product of x and y: ", dot_xy)

The dot product of v and w:  219
The dot product of x and v:  [29 77]
The dot product of x and y:  [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Concatenate x and y along rows using np.vstack()
concat_xy_row = np.concatenate((x, y))
print("Concatenated x and y along rows :\n", concat_xy_row)

# Concatenate v and w along columns using np.hstack()
concat_vw_col = np.hstack((v,w))
print("Concatenated v and w along columns using np.hstack():\n", concat_vw_col)

Concatenated x and y along rows :
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenated v and w along columns using np.hstack():
 [ 9 10 11 12]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
#concat_xv_row = np.concatenate((x, v))
#np.concatenate requires that all input arrays have the same number of dimensions.
#Thus, trying to concatenate x and v directly results in a ValueError.

**Problem - 4: Matrix Operations:**


 For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:

1. Prove A.A−1 = I.

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

A_inverse = np.linalg.inv(A)
result = np.dot(A, A_inverse)

identity_matrix = np.eye(2)
#np.allclose() checks if two arrays are element-wise equal within a tolerance.
print(np.allclose(result, identity_matrix)) #Prints True if close enough


print("Matrix A:\n", A)
print("\nInverse of A:\n", A_inverse)
print("\nA * A_inverse (using np.dot):\n", result)
print("\nIdentity Matrix:\n", identity_matrix)

True
Matrix A:
 [[3 4]
 [7 8]]

Inverse of A:
 [[-2.    1.  ]
 [ 1.75 -0.75]]

A * A_inverse (using np.dot):
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Identity Matrix:
 [[1. 0.]
 [0. 1.]]


2. Prove AB ̸= BA.

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# Compute AB
AB = np.dot(A, B)
# Compute BA
BA = np.dot(B, A)
# Print the results
print("AB =\n", AB)
print("BA =\n", BA)

# Check if AB is equal to BA
print("Is AB equal to BA?\n", np.array_equal(AB, BA))


AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
Is AB equal to BA?
 False


3. Prove (AB)T = BT AT .

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# Compute AB
AB = np.dot(A, B)

# Compute (AB)^T using np.transpose()
AB_transpose = np.transpose(AB)

# Compute B^T and A^T using np.transpose()
B_transpose = np.transpose(B)
A_transpose = np.transpose(A)

# Compute B^T * A^T
BT_AT = np.dot(B_transpose, A_transpose)

# Print the results
print("(AB)^T =\n", AB_transpose)
print("B^T * A^T =\n", BT_AT)

# Check if (AB)^T is equal to B^T * A^T
print("Is (AB)^T equal to B^T * A^T?\n", np.array_equal(AB_transpose, BT_AT))

(AB)^T =
 [[23 51]
 [13 29]]
B^T * A^T =
 [[23 51]
 [13 29]]
Is (AB)^T equal to B^T * A^T?
 True


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

In [ ]:
# Define the coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

# Define the constant matrix B
B = np.array([-1, -3, 9])

# Compute the inverse of A
A_inv = np.linalg.inv(A)

# Solve for X using the inverse of A
X = np.dot(A_inv, B)
print(X)
# Print the solution
print(f"The value of x is {X[0]}")
print(f"The value of y is {X[1]}")
print(f"The value of z is {X[2]}")

[ 2.  1. -2.]
The value of x is 2.0
The value of y is 1.0
The value of z is -2.0


In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
import time
import numpy as np

# Define the size of the lists/arrays
size = 1_000_000

# Create two lists of size 1,000,000
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

# Measure the time taken for element-wise addition using Python lists
start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()

print(f"Time taken for element-wise addition using Python lists: {end_time - start_time:.6f} seconds")

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(size)
array2 = np.arange(size)

# Measure the time taken for element-wise addition using NumPy arrays
start_time = time.time()
result_array = array1 + array2
end_time = time.time()

print(f"Time taken for element-wise addition using NumPy arrays: {end_time - start_time:.6f} seconds")

Time taken for element-wise addition using Python lists: 0.160706 seconds
Time taken for element-wise addition using NumPy arrays: 0.006156 seconds


2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
import time
import numpy as np

# Define the size of the lists/arrays
size = 1_000_000

# Create two lists of size 1,000,000
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

# Measure the time taken for element-wise multiplication using Python lists
start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()

print(f"Time taken for element-wise multiplication using Python lists: {end_time - start_time:.6f} seconds")

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(size)
array2 = np.arange(size)

# Measure the time taken for element-wise multiplication using NumPy arrays
start_time = time.time()
result_array = array1 * array2
end_time = time.time()

print(f"Time taken for element-wise multiplication using NumPy arrays: {end_time - start_time:.6f} seconds")

Time taken for element-wise multiplication using Python lists: 0.328028 seconds
Time taken for element-wise multiplication using NumPy arrays: 0.009321 seconds


3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
import time
import numpy as np

# Define the size of the lists/arrays
size = 1_000_000

# Create two lists of size 1,000,000
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

# Measure the time taken for computing the dot product using Python lists
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
end_time = time.time()

print(f"Time taken for computing the dot product using Python lists: {end_time - start_time:.6f} seconds")

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(size)
array2 = np.arange(size)

# Measure the time taken for computing the dot product using NumPy arrays
start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()

print(f"Time taken for computing the dot product using NumPy arrays: {end_time - start_time:.6f} seconds")

Time taken for computing the dot product using Python lists: 0.185333 seconds
Time taken for computing the dot product using NumPy arrays: 0.001877 seconds


4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [ ]:
import time
import numpy as np

# Define the size of the matrices
size = 1000

# Create two matrices of size 1000x1000 using Python lists
matrix1 = [[i + j for j in range(size)] for i in range(size)]
matrix2 = [[i - j for j in range(size)] for i in range(size)]

# Measure the time taken for matrix multiplication using Python lists
start_time = time.time()
result_matrix = [[sum(a * b for a, b in zip(row, col)) for col in zip(*matrix2)] for row in matrix1]
end_time = time.time()

print(f"Time taken for matrix multiplication using Python lists: {end_time - start_time:.6f} seconds")

# Create two NumPy arrays of size 1000x1000
array1 = np.array(matrix1)
array2 = np.array(matrix2)

# Measure the time taken for matrix multiplication using NumPy arrays
start_time = time.time()
result_array = np.dot(array1, array2)
end_time = time.time()

print(f"Time taken for matrix multiplication using NumPy arrays: {end_time - start_time:.6f} seconds")

Time taken for matrix multiplication using Python lists: 172.310290 seconds
Time taken for matrix multiplication using NumPy arrays: 1.572262 seconds
